name: Rust

on:
  push:
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose --lib
    - name: Run xperf
      run: xperf -start "NT Kernel Logger" -on latency - stackwalk profile -start "usersession" -on Microsoft-Windows-DxgKrnl:1:1
    - name: Stop xperf
      run: xperf -stop "NT Kernel Logger" -stop "usersession" -d out.etl
